modLoader="javafml" #mandatory

loaderVersion="[1,)" #mandatory

license="MIT"

[[mods]] #mandatory
modId="pride" #mandatory
version="${version}" #mandatory
displayName="Pride Lib" #mandatory
logoFile="assets/pride/icon.png" #optional
logoBlur=false
authors="Emi, unascribed, LambdAurora, LostPattern" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''A unified library for data-driven flags.'''
